server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/buddhalike?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


